version: latest

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 5434:5432